In [2]:
import numpy as np
print(np.__version__)

1.21.1


In [12]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [13]:
print(arr.shape)

(10,)


In [4]:
print(np.arange(1,20,3))
print(np.linspace(1,20,3))

[ 1  4  7 10 13 16 19]
[ 1.  10.5 20. ]


Slicing

In [14]:
print(arr[0], arr[1], arr[-1])
print(arr[2:5])
print(arr[5:])
print(arr[-3:-1])

10 20 100
[30 40 50]
[ 60  70  80  90 100]
[80 90]


Search

In [19]:
print(np.where(arr == 40))

[3]


In [64]:
print(np.where(arr % 2 == 0))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)


Filter

In [36]:
print(arr % 2 == 0)
print(arr[arr % 2 == 0])

[ True  True  True  True  True  True  True  True  True  True]
[ 10  20  30  40  50  60  70  80  90 100]


In [21]:
filter = [True, False, True, False, True,True, False, False, False, True]
print(arr[filter])

[ 10  30  50  60 100]


In [38]:
print(np.logical_and(arr>20, arr<80))
print(arr[np.logical_and(arr>20, arr<80)])

[False False  True  True  True  True  True False False False]
[30 40 50 60 70]


In [47]:
print((arr > 20) & (arr < 80))
print(arr[(arr > 20) & (arr < 80)])

[False False  True  True  True  True  True False False False]
[30 40 50 60 70]


All/Any

In [60]:
print(np.all(arr % 10 == 0))
print(np.any(arr > 100))

True
False


Map

In [62]:
print(list(map(lambda x: x+1, arr)))

[11, 21, 31, 41, 51, 61, 71, 81, 91, 101]


Sort

In [72]:
print(np.sort([5,1,3]))
print(np.sort(["apple", "mango", "banana"]))

[1 3 5]
['apple' 'banana' 'mango']


In [76]:
x = np.array([5,1,3])
print(np.argsort(x))
print(x[np.argsort(x)])

[1 2 0]
[1 3 5]


In [83]:
a = [4, -3, 2, -1]
a.sort(key=lambda x: abs(x))
print(a)

[-1, 2, -3, 4]


In [84]:
print(sorted([4,-3,2,-1], key=lambda x: abs(x)))
print(sorted([4,-3,2,-1], key=lambda x: abs(x), reverse=True))

[-1, 2, -3, 4]
[4, -3, 2, -1]


In [94]:
from functools import cmp_to_key
def comp(val1, val2):
  return val2-val1
print(sorted([5,1,3,2], key=cmp_to_key(comp)))

[5, 3, 2, 1]


In [97]:
from functools import cmp_to_key
print(sorted([5, 1, 3, 2], key=cmp_to_key(lambda val1, val2: val2-val1)))


[5, 3, 2, 1]


Join

In [99]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
print(np.concatenate((arr1, arr2)))

[ 1  2  3  4  5 11 12 13 14 15]


In [101]:
# Stacking along column
print(np.stack((arr1, arr2), axis=0))

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [102]:
# Stacking along depth
print(np.stack((arr1, arr2), axis=1))


 [[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]


In [111]:
arrays = [np.random.randn(3, 4, 5) for _ in range(10)]
for axis in range(4):
  print(np.stack(arrays, axis=axis).shape)


(10, 3, 4, 5)
(3, 10, 4, 5)
(3, 4, 10, 5)
(3, 4, 5, 10)


2d Arrays

In [114]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [115]:
print(arr2d.shape)

(2, 3)


In [116]:
print(arr2d.reshape(6))

[1 2 3 4 5 6]


In [121]:
print(arr2d.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [123]:
print(arr2d[1:,0:2])

[[4 5]]


In [124]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [128]:
print(arr2d != 5)
print(arr2d[arr2d != 5])

[[ True  True  True]
 [ True False  True]]
[1 2 3 4 6]


In [132]:
print(arr2d[0] % 2 != 0)
print(arr2d[0][arr2d[0] % 2 != 0])

[ True False  True]
[1 3]


Math

In [9]:
arr2d = [[5,3,5,2],[2,1,3,4]]
np.mean(arr2d, axis=0)

array([3.5, 2. , 4. , 3. ])

In [21]:
np.mean(arr2d, axis=(0,1))

3.125

In [22]:
arr = np.random.random((4,2,3,5))
arr.shape

(4, 2, 3, 5)

In [29]:
print(np.mean(arr, axis=0).shape)
print(np.mean(arr, axis=1).shape)
print(np.mean(arr, axis=2).shape)
print(np.mean(arr, axis=(0,2)).shape)
print(np.mean(arr, axis=(0,2,3)).shape)

(2, 3, 5)
(4, 3, 5)
(4, 2, 5)
(2, 5)
(2,)
