In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.7.0'

In [2]:
mat1 = tf.constant(np.array([[1,2],[3,4]]))
mat1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [3]:
mat2 = tf.constant(np.array([[4, 1], [2,3]]))
mat_add = tf.add(mat1, mat2)
mat_prod = tf.matmul(mat1, mat2)
print(mat_add)
print(mat_prod)

tf.Tensor(
[[5 3]
 [5 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 8  7]
 [20 15]], shape=(2, 2), dtype=int32)


In [4]:
num = tf.Variable(10, name="num")
print(num)
num.assign(20)
print(num)

<tf.Variable 'num:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'num:0' shape=() dtype=int32, numpy=20>


In [5]:
def f(x, y):
  return x ** 2 + y
tf_fun = tf.function(f)

x = tf.constant([2, 3])
y = tf.constant([3, -2])
tf_fun(x, y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7])>